### ISSUE TITLE
Skill Level 20

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1443]
Hello,

There is a specific behaviour for the level 20 when an UCI engine supports the option "Skill Level" from 1 to 20 (like Stockfish). I did a table to explain the different cases :

- Config = the level set in the configuration (engine dialog)
- Game = the selected level to start a new game from the main UI
- Sent = this is the level received by the UCI engine (setoption)

| Config | Game | Sent |
|:------:|:----:|:----:|
| 10     | 10   | 10   |
| 10     | 15   | 15   |
| 10     | 20   | 10   |
| 20     | 10   | 10   |
| 20     | 15   | 15   |
| 20     | 20   | 20   |

The conclusion is that we get the level of the default configuration if we start a new game with the level 20 from the UI. For Stockfish, this issue is transparent because 20 is the default level, but can this be considered as an issue in the general case ?

Thank you.

PS: your website is not reachable for many days now

**Comment by gbtami** [comment]
@ecrucru I fixed this in https://github.com/pychess/pychess/commit/fbaed03d48b566d2918408c30f4972fe22e3db65
To test it with anticrux you have to change the option name from "level" to "Skill Level". Because this option is not UCI standard I don't want to hardwire different names for different engines for the same thing, and Stockfish introduced it first :wink:

**Comment by ecrucru** [comment]
Hello,

Yes indeed, I had changed the name of the option some days ago because I noticed that something was done specifically in pyChess for Stockfish (serendipity!) and this is fine.

In fact, I am unable to test your change because 'sslproto' is not resolved (since you started to use asyncio). However we agree on what you changed in the code. And you can leave the commented line as it was before (the sole mention of Stockfish is sufficient).

At this [line](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L94), Stockfish Level 20 is not handicaped. It is a level like the other ones, so there is normally no reason to exclude Skill Level 20, and so your change should be OK.

Thank you.

**Comment by gbtami** [comment]
@ecrucru can you paste your console output of this 'sslproto' is not resolved please?

**Comment by ecrucru** [comment]
It is a Debian 8 (Jessie) with the dependencies of your file INSTALL :
![out](https://user-images.githubusercontent.com/24614488/29384709-5d239e7c-82d5-11e7-9f46-06dc760b676f.png)

**Comment by gbtami** [comment]
Can you git pull and try it again now please?

**Comment by ecrucru** [comment]
![pychess2](https://user-images.githubusercontent.com/24614488/29425134-78783d42-8382-11e7-9102-653f17673adb.png)

**Comment by gbtami** [comment]
This is because python3-pexpect version is too old (3.2) in Jessie. See https://packages.debian.org/search?keywords=python3-pexpect&searchon=names&suite=all&section=all

You can install a newer one as root with adding jessie-backports line to your /etc/apt/sources.list like:
deb http://ftp.debian.org/debian jessie-backports main
then
apt-get update
apt-get -t jessie-backports install python3-pexpect

or

apt-get remove python3-pexpect
pip3 install pexpect

**Comment by ecrucru** [comment]
I have reverted #1444 for the tests and everything is fine.
Thanks
