### ISSUE TITLE
How to install pychess-0.99.3-1.py37.noarch  on Fedora 28/29

### ISSUE THREAD

**Issue by jule009** [pychess/pychess#1708]
Hi,
On Fedora 29 there is installed pychess-0.12.4-13.fc29.noarch                  
python3-gstreamer1-1.14.4-1.fc29.x86_64         

Would like to run the newest version of Pychess on F28/F29.
That`s my result:

Installiert:
  pychess-0.99.3-1.py37.noarch                                                 
Fertig.

[joerg@localhost ~]$ pychess
/usr/local/bin/pychess:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
Failed to create splash screen
ERROR: Could not import modules.
Please try to run pychess as stated in the INSTALL file
[joerg@localhost ~]$ 

I have problems to find and install the "right" version of Gtk for pychess-0.99.3-1.py37.noarch.
Did anyone install pychess-0.99.3-1.py37.noarch on F29/F28?
Kind regards

**Comment by gbtami** [comment]
Reproduced.

**Comment by gbtami** [comment]
Seems /usr/local/lib/python3.7/dist-packages/ is missing from sys.path on Fedora's python. Strange.
As a workaround you can start pychess something like:
PYTHONPATH=/usr/local/lib/python3.7/dist-packages/ pychess

**Comment by jule009** [comment]
Using the workaround I can start the newest Pychess version on F29.
On F28 there is still another Problem: See log:

[joerg@localhost ~]$ pychess
Failed to create splash screen
ERROR: PyChess requires python-cairo to be installed.

[joerg@localhost ~]$ sudo PYTHONPATH=/usr/local/lib/python3.7/dist-packages/ pychess
Failed to create splash screen
ERROR: PyChess requires python-cairo to be installed.
[joerg@localhost ~]$ sudo dnf info pychess
Letzte Prüfung auf abgelaufene Metadaten: vor 5 days, 9:42:23 am Mi 14 Nov 2018 08:58:09 CET.
Installierte Pakete
Name         : pychess
Version      : 0.99.3
Release      : 1.py37
Arch         : noarch
Größe        : 27 M
Quelle       : pychess-0.99.3-1.py37.src.rpm

...... There is installed:
Paket python2-cairo-1.16.3-1.fc28.x86_64 ist bereits installiert
..... possibly not the right model version.

I don't know, if its my error or not.
Kind regards

**Comment by gbtami** [comment]
I think Fedora 28 doesn't have python 3.7.x just 3.6.x, so try with
PYTHONPATH=/usr/local/lib/python3.6/dist-packages/ pychess

**Comment by jule009** [comment]
Have tried this workaround for Pychess F28, doesn't work, see log:
[joerg@localhost ~]$ sudo PYTHONPATH=/usr/local/lib/python3.6/dist-packages/ pychess
[sudo] Passwort für joerg: 
Failed to create splash screen
ERROR: PyChess requires python-cairo to be installed.
[joerg@localhost ~]$ dnf info pychess
Letzte Prüfung auf abgelaufene Metadaten: vor 10 days, 20:05:16 am Fr 09 Nov 2018 14:23:52 CET.
Installierte Pakete
Name         : pychess
Version      : 0.99.3

Installed is on my F28:
Name         : python2-cairo
Version      : 1.16.3
Release      : 1.fc28
Arch         : x86_64
Größe        : 311 k
Quelle       : pycairo-1.16.3-1.fc28.src.rpm
and
Name         : python3-cairo
Version      : 1.16.3
Release      : 1.fc28
Arch         : x86_64
Größe        : 307 k
Quelle       : pycairo-1.16.3-1.fc28.src.rpm


Release      : 1.py37
Arch         : noarch
Größe        : 27 M
Quelle       : pychess-0.99.3-1.py37.src.rpm
Paketquelle  : @System
Aus Paketque : @commandline

Kind regards

**Comment by gbtami** [comment]
Works for me.
1. download https://github.com/pychess/pychess/releases/download/0.99.3/pychess-0.99.3-1.py36.noarch.rpm
2. cd to your Downloads
3. sudo dnf install pychess-0.99.3-1.py36.noarch.rpm
4. PYTHONPATH=/usr/local/lib/python3.6/dist-packages/ pychess

**Comment by gbtami** [comment]
Btw the first time run of pychess has problem with anaconda. Anaconda is the installation program used by Fedora and the same time it is a chess engine in pychess autodetection list. Similar problem as https://github.com/pychess/pychess/issues/1695 
(Already fixed in current git)

**Comment by jule009** [comment]
Now it's ok. My fault was downloading ....py37... instead of ...py36...
Thank You very much.
Kind regards

**Comment by jule009** [comment]
Sorry, there is still a problem, I didn't test so far the last time. The chess machine anaconda is not found (F28/F29). Kind regards
![bildschirmfoto vom 2018-11-25 18-41-15](https://user-images.githubusercontent.com/40624880/48982445-d3b61200-f0e2-11e8-8447-4def01095e1f.png)

**Comment by gbtami** [comment]
The fix exist in git master and will be available in next release.
If you want to run the latest pychess from sources you have to install git first, then
```
git clone https://github.com/pychess/pychess.git
cd pychess
./pychess
```
