### ISSUE TITLE
Index out of range upon game creation

### ISSUE THREAD

**Issue by xero-lib** [pychess/pychess#1846]
I have installed PyChess through the software manager and through pacman/yay. I have also tried running PyChess through a clone of the git repo. All of them give me the same error when attempting to create a new game:
```py
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Main.py", line 251, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 562, in run
    cls._ensureReady()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 206, in _init
    updateCombos(discoverer)
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 201, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range
```
All dependencies appear to be installed.

**Comment by xero-lib** [comment]
I'm hoping I'm just missing something because I really loved PyChess. I would hate to stop using it because of this random error.

**Comment by gbtami** [comment]
Maybe your PC contains "3rd party" asyncio module? Try to uninstall it. asyncio is official part of Python from 3.4, so installing another one can make trouble.

**Comment by xero-lib** [comment]
> Maybe your PC contains "3rd party" asyncio module? Try to uninstall it. asyncio is official part of Python from 3.4, so installing another one can make trouble.

The only results for `asyncio` is `python-asyncio` which I assume is the official module.

**Comment by xero-lib** [comment]
If I just run `pychess` as it is in my path, the immediate response is:
```py
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
```

If I run it in the cloned folder with `python`, the result is:
```py
pychess:238: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app)
```

And then, as usual, when I try to create a new game:
```py
(pychess:7436): Gtk-WARNING **: 11:23:48.049: Can't set a parent on widget which has a parent
Traceback (most recent call last):
  File "/home/helix/Scripts/pychess/lib/pychess/Main.py", line 252, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 562, in run
    cls._ensureReady()
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 206, in _init
    updateCombos(discoverer)
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 201, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range
count() not went well on engine gnuchess
```

**Comment by gbtami** [comment]
python-asyncio is exactly what I'm talking about.
It is an old asyncio package before asyncio started to be part of Python. You definitely don't want to use it for anything today :)
Uninstall it please!

**Comment by xero-lib** [comment]
> python-asyncio is exactly what I'm talking about.
> It is an old asyncio package before asyncio started to be part of Python. You definitely don't want to use it for anything today :)
> Uninstall it please!

What should I use instead?

**Comment by xero-lib** [comment]
> python-asyncio is exactly what I'm talking about.
> It is an old asyncio package before asyncio started to be part of Python. You definitely don't want to use it for anything today :)
> Uninstall it please!

After uninstalling `python-asyncio` I `pip install`ed `asyncio` but the problem persists.

**Comment by xero-lib** [comment]
```py
helix:~/Scripts/pychess $ python3.8 pychess
pychess:238: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app):

(pychess:8091): Gtk-WARNING **: 22:04:56.870: Can't set a parent on widget which has a parent
Traceback (most recent call last):
  File "/home/helix/Scripts/pychess/lib/pychess/Main.py", line 252, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 562, in run
    cls._ensureReady()
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 206, in _init
    updateCombos(discoverer)
  File "/home/helix/Scripts/pychess/lib/pychess/widgets/newGameDialog.py", line 201, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range
```

```py
helix:~/Scripts/pychess $ pip install asyncio
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: asyncio in /usr/lib/python3.8/site-packages (3.4.3)
```

**Comment by gbtami** [comment]
@xero-lib please DON'T install third party asyncio packages at all!
asyncio module is part of official Python3 install already!

**Comment by xero-lib** [comment]
This fixed nothing. Same error.

**Comment by xero-lib** [comment]
Why would you close this question without confirmation that the problem is resolved? Regardless, it isn't. I fully removed `asyncio` from my system, but I receive the exact same error.

**Comment by gbtami** [comment]
If you still get `SyntaxError: invalid syntax` then you still have third party packages conflicting with built in Python modules.

**Comment by ecrucru** [comment]
Hello @xero-lib

The error `IndexError: list index out of range` may be linked to the detection of the engines. Can you provide a screenshot of your engines: PyChess > Edit > Engines ?

For a proper use of PyChess starting from a fresh download, it is very recommended to install the package `stockfish`.

Then as a last raw solution, can you edit the file `pychess/lib/pychess/widgets/engineList.py` and switch "gnuchess" to NO_AUTO_DETECT.

HTH

**Comment by xero-lib** [comment]
> Hello @xero-lib
> 
> The error `IndexError: list index out of range` may be linked to the detection of the engines. Can you provide a screenshot of your engines: PyChess > Edit > Engines ?
> 
> For a proper use of PyChess starting from a fresh download, it is very recommended to install the package `stockfish`.
> 
> Then as a last raw solution, can you edit the file `pychess/lib/pychess/widgets/engineList.py` and switch "gnuchess" to NO_AUTO_DETECT.
> 
> HTH
I have installed the stockfish package through the AUR, is there another way I should go bout that?

Also, here are the screenshots of my engines page. If you need the options as well, I'll send them. I'll try your proposed solution in the mean time.

![image](https://user-images.githubusercontent.com/54485853/86502995-0f10cc00-bd6f-11ea-88f7-a466eb553107.png)
![image](https://user-images.githubusercontent.com/54485853/86502999-17690700-bd6f-11ea-9b7b-a65a5b27c505.png)
![image](https://user-images.githubusercontent.com/54485853/86503002-1df77e80-bd6f-11ea-8f72-a6a72df01d6a.png)
![image](https://user-images.githubusercontent.com/54485853/86503003-23ed5f80-bd6f-11ea-80ca-bbacf9ed03d9.png)

**Comment by xero-lib** [comment]
> If you still get `SyntaxError: invalid syntax` then you still have third party packages conflicting with built in Python modules.

I don't get invalid syntax anywhere that I see in my errors.

**Comment by xero-lib** [comment]
> Hello @xero-lib
> 
> The error `IndexError: list index out of range` may be linked to the detection of the engines. Can you provide a screenshot of your engines: PyChess > Edit > Engines ?
> 
> For a proper use of PyChess starting from a fresh download, it is very recommended to install the package `stockfish`.
> 
> Then as a last raw solution, can you edit the file `pychess/lib/pychess/widgets/engineList.py` and switch "gnuchess" to NO_AUTO_DETECT.
> 
> HTH

I have no file `pychess/lib/pychess/widgets/engineList.py`. The only files in that directory are `__pycache__/` and `pydock/`.

**Comment by xero-lib** [comment]
> Hello @xero-lib
> 
> The error `IndexError: list index out of range` may be linked to the detection of the engines. Can you provide a screenshot of your engines: PyChess > Edit > Engines ?
> 
> For a proper use of PyChess starting from a fresh download, it is very recommended to install the package `stockfish`.
> 
> Then as a last raw solution, can you edit the file `pychess/lib/pychess/widgets/engineList.py` and switch "gnuchess" to NO_AUTO_DETECT.
> 
> HTH

I don't have the file `engineList.py` in the widgets directory.
![image](https://user-images.githubusercontent.com/54485853/86503256-0968b580-bd72-11ea-8bce-463f461831a0.png)

**Comment by xero-lib** [comment]
It is however under the `pychess/lib/pychess/Players/` directory... I'll try that.

**Comment by xero-lib** [comment]
![image](https://user-images.githubusercontent.com/54485853/86503413-98c29880-bd73-11ea-8b5a-d16735a1ba95.png)
Changing `gnuchess` to `NO_AUTO_DETECT` didn't change it.

**Comment by xero-lib** [comment]
> Changing `gnuchess` to `NO_AUTO_DETECT` didn't change it.
![image](https://user-images.githubusercontent.com/54485853/86503474-1090c300-bd74-11ea-97ff-d3e5df2388e2.png)

and yes I saved the file.

**Comment by ecrucru** [comment]
Unfortunately, I can't reproduce your issue at all. On the home page, you should be able to see "Human being" as a possible opponent at least.

Let's try some steps :

1) May you try to reset the config ? The files should be at : `/home/helix/.config/pychess`

2) May you add the 3 middle lines in `newGameDialog.py` around line 201, and let us know what is displayed in the console ?

```
            cls.widgets["playVariant1Radio"].set_tooltip_text(variants[variant1].__desc__)
            variant2 = conf.get("ngvariant2")
            cls.widgets["playVariant2Radio"].set_tooltip_text(variants[variant2].__desc__)

            print(variant)
            for item in playerItems[variant]:
                print(item)

            data = [(item[0], item[1]) for item in playerItems[variant]]
            uistuff.updateCombo(cls.widgets["blackPlayerCombobox"], data)
            uistuff.updateCombo(cls.widgets["whitePlayerCombobox"], data)
```

3) May you communicate your engines in raw format ? The JSON file is in the folder mentioned at 1).

4) At last raw workaround, may you switch all the engines to `NO_AUTO_DETECT` ? They can be manually added from the user interface later.

Thanks for your inputs.

**Comment by xero-lib** [comment]
> Unfortunately, I can't reproduce your issue at all. On the home page, you should be able to see "Human being" as a possible opponent at least.
> 
> Let's try some steps :
> 
>     1. May you try to reset the config ? The files should be at : `/home/helix/.config/pychess`
> 
>     2. May you add the 3 middle lines in `newGameDialog.py` around line 201, and let us know what is displayed in the console ?
> 
> 
> ```
>             cls.widgets["playVariant1Radio"].set_tooltip_text(variants[variant1].__desc__)
>             variant2 = conf.get("ngvariant2")
>             cls.widgets["playVariant2Radio"].set_tooltip_text(variants[variant2].__desc__)
> 
>             print(variant)
>             for item in playerItems[variant]:
>                 print(item)
> 
>             data = [(item[0], item[1]) for item in playerItems[variant]]
>             uistuff.updateCombo(cls.widgets["blackPlayerCombobox"], data)
>             uistuff.updateCombo(cls.widgets["whitePlayerCombobox"], data)
> ```
> 
>     1. May you communicate your engines in raw format ? The JSON file is in the folder mentioned at 1).
> 
>     2. At last raw workaround, may you switch all the engines to `NO_AUTO_DETECT` ? They can be manually added from the user interface later.
> 
> 
> Thanks for your inputs.

I've removed `/home/helix/.config/pychess` entirely before.

I tried to `git pull` but it broke my entire install, now every time I try to do anything, I get:
```py
Traceback (most recent call last):
  File "pychess", line 269, in <module>
    create_task(start(gtk_app))
  File "/usr/lib/python3.8/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'start' was never awaited
  %!PS-Adobe-3.0
```

**Comment by xero-lib** [comment]
> @xero-lib please DON'T install third party asyncio packages at all!
> asyncio module is part of official Python3 install already!

Not on my computer
```py
pychess:238: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app):

(pychess:27300): Gtk-WARNING **: 22:19:03.671: Can't set a parent on widget which has a parent
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
```

**Comment by xero-lib** [comment]
> Unfortunately, I can't reproduce your issue at all. On the home page, you should be able to see "Human being" as a possible opponent at least.
> 
> Let's try some steps :
> 
>     1. May you try to reset the config ? The files should be at : `/home/helix/.config/pychess`
> 
>     2. May you add the 3 middle lines in `newGameDialog.py` around line 201, and let us know what is displayed in the console ?
> 
> 
> ```
>             cls.widgets["playVariant1Radio"].set_tooltip_text(variants[variant1].__desc__)
>             variant2 = conf.get("ngvariant2")
>             cls.widgets["playVariant2Radio"].set_tooltip_text(variants[variant2].__desc__)
> 
>             print(variant)
>             for item in playerItems[variant]:
>                 print(item)
> 
>             data = [(item[0], item[1]) for item in playerItems[variant]]
>             uistuff.updateCombo(cls.widgets["blackPlayerCombobox"], data)
>             uistuff.updateCombo(cls.widgets["whitePlayerCombobox"], data)
> ```
> 
>     1. May you communicate your engines in raw format ? The JSON file is in the folder mentioned at 1).
> 
>     2. At last raw workaround, may you switch all the engines to `NO_AUTO_DETECT` ? They can be manually added from the user interface later.
> 
> 
> Thanks for your inputs.

I don't know what you mean by "may I communicate the engines in raw format"

Also, the output of the modified application is now:
```py
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
0
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Main.py", line 251, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 577, in run
    cls._ensureReady()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 221, in _init
    updateCombos(discoverer)
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 211, in updateCombos
    for item in playerItems[variant]:
IndexError: list index out of range

```

**Comment by gbtami** [comment]
"@xero-lib please DON'T install third party asyncio packages at all!
asyncio module is part of official Python3 install already!"

"Not on my computer"
See https://docs.python.org/3/library/asyncio.html#module-asyncio

If you see `SyntaxError: invalid syntax` this clearly indicates that you have that third party conflicting asyncio package installed.
Until you don't uninstall it pychess can't start, because it uses standard Python asyncio module.

"I tried to git pull but it broke my entire install, now every time I try to do anything, I get:"
This was caused my late night commit. Fixed it right now. Try `git pull `again

**Comment by xero-lib** [comment]
> "@xero-lib please DON'T install third party asyncio packages at all!
> asyncio module is part of official Python3 install already!"
> 
> "Not on my computer"
> See https://docs.python.org/3/library/asyncio.html#module-asyncio
> 
> If you see `SyntaxError: invalid syntax` this clearly indicates that you have that third party conflicting asyncio package installed.
> Until you don't uninstall it pychess can't start, because it uses standard Python asyncio module.
> 
> "I tried to git pull but it broke my entire install, now every time I try to do anything, I get:"
> This was caused my late night commit. Fixed it right now. Try `git pull `again

I've uninstalled every asyncio package on my computer. I've done a full system search of any file with async in the name and removed all relevant python packages.

**Comment by gbtami** [comment]
If you see SyntaxError: invalid syntax this clearly indicates that you have that third party conflicting asyncio package installed.
Until you don't uninstall it pychess can't start, because it uses standard Python asyncio module.

**Comment by xero-lib** [comment]
> "I tried to git pull but it broke my entire install, now every time I try to do anything, I get:"
> This was caused my late night commit. Fixed it right now. Try `git pull `again

Beautiful, the application runs again. Same error though. I really do appreciate your continued support on this, I understand I haven't been the kindest I could have been, I'm just dealing with stuff afk. If Discord would be easier, let me know and I'll give you my tag.

![image](https://user-images.githubusercontent.com/54485853/86528851-9d6d7680-be71-11ea-9dc6-3c3a6dda91d1.png)


![image](https://user-images.githubusercontent.com/54485853/86528855-a3fbee00-be71-11ea-9aba-e969386843b6.png)

**Comment by xero-lib** [comment]
> If you see SyntaxError: invalid syntax this clearly indicates that you have that third party conflicting asyncio package installed.
> Until you don't uninstall it pychess can't start, because it uses standard Python asyncio module.



All locations of asyncio on my computer can be found in this document. 

[asyncio.locations.txt](https://github.com/pychess/pychess/files/4874635/asyncio.locations.txt)

**Comment by gbtami** [comment]
If `SyntaxError: invalid syntax` gone the third party asyncio part of your issue is solved. 

The remaining` IndexError: list index out of range` is another (unrelated) one.
Please try to remove your engines config file  ~/.config/pychess/engines.json

**Comment by xero-lib** [comment]
> If `SyntaxError: invalid syntax` gone the third party asyncio part of your issue is solved.
> 
> The remaining` IndexError: list index out of range` is another (unrelated) one.
> Please try to remove your engines config file ~/.config/pychess/engines.json

I need the supposed '3rd part module' for several other applications I have, that I had to uninstall, such as v3n0m and several others.

But the new error is:

```py
helix:~/Scripts/pychess $ pychess
/usr/bin/pychess:238: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app):

(pychess:14904): Gtk-WARNING **: 12:00:03.250: Can't set a parent on widget which has a parent
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 45, in <module>
    from . import staggered
  File "/usr/lib/python3.8/asyncio/staggered.py", line 6, in <module>
    import typing
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Main.py", line 251, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 562, in run
    cls._ensureReady()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 206, in _init
    updateCombos(discoverer)
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 201, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range
```

**Comment by gbtami** [comment]
Seems you have another not compatible third-party (typing?) python package.
At least pychess itself never used Python typing module at all, but` AttributeError: type object 'Callable' has no attribute '_abc_registry'` clearly indicates that you have one installed from maybe pypi again.

If you are using apps (v3n0m and others?) who makes your official Python3 modules unusable because they install conflicting packages there will never be any guarantee to run normal apps without error.

Again asyncio and typing are built in modules in Python3 from years!
https://docs.python.org/3.4/library/asyncio.html#module-asyncio
https://docs.python.org/3.5/library/typing.html#module-typing

Apps installing old third-party conflicting modules are simply BAD software! Don't use them, or ask his developers to fix their app (via using built in Python3 modules instead of installing unneeded and conflicting old stuff from pypi).

**Comment by gbtami** [comment]
I'm closing this now, because I don't want to waste more time to fix users broken Python3 install. Sry.

**Comment by xero-lib** [comment]
> I'm closing this now, because I don't want to waste more time to fix users broken Python3 install. Sry.

That was never the error causing the app to be unusable.

The persistent error is still:
```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Main.py", line 251, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 562, in run
    cls._ensureReady()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 206, in _init
    updateCombos(discoverer)
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 201, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range
```

Which to my knowledge isn't caused by a 3rd party python package. Please reopen this.

**Comment by xero-lib** [comment]
> Unfortunately, I can't reproduce your issue at all. On the home page, you should be able to see "Human being" as a possible opponent at least.
> 
> Let's try some steps :
> 
>     1. May you try to reset the config ? The files should be at : `/home/helix/.config/pychess`
> 
>     2. May you add the 3 middle lines in `newGameDialog.py` around line 201, and let us know what is displayed in the console ?
> 
> 
> ```
>             cls.widgets["playVariant1Radio"].set_tooltip_text(variants[variant1].__desc__)
>             variant2 = conf.get("ngvariant2")
>             cls.widgets["playVariant2Radio"].set_tooltip_text(variants[variant2].__desc__)
> 
>             print(variant)
>             for item in playerItems[variant]:
>                 print(item)
> 
>             data = [(item[0], item[1]) for item in playerItems[variant]]
>             uistuff.updateCombo(cls.widgets["blackPlayerCombobox"], data)
>             uistuff.updateCombo(cls.widgets["whitePlayerCombobox"], data)
> ```
> 
>     1. May you communicate your engines in raw format ? The JSON file is in the folder mentioned at 1).
> 
>     2. At last raw workaround, may you switch all the engines to `NO_AUTO_DETECT` ? They can be manually added from the user interface later.
> 
> 
> Thanks for your inputs.

I am not able to see human being as an opponent. 
![image](https://user-images.githubusercontent.com/54485853/86540995-bc4e2600-bece-11ea-862b-2950c270eec9.png)
